### ISSUE TITLE
Verbindung zur Datenbank aufbauen

### ISSUE THREAD

**Issue by Rob-Walter** [SmollClover/Jahresprojekt-FA31#11]

**Comment by SmollClover** [comment]
Hibernate und PostgreSQL dependencies wurden bereits im commit 89fb542b660b6ec1c13cbd4780b97fcd6814b4aa auf dem `database`-Branch hinzugefügt

**Comment by SmollClover** [comment]
Da das Projekt neu begonnen wurde, wurde ein erneuter versuch gestartet mit Commit b054ba1

**Comment by SmollClover** [comment]
Scheint soweit gut zu sein. 
In Review fürs testen

**Comment by SmollClover** [comment]
Done
