### ISSUE TITLE
Navigation implementieren

### ISSUE THREAD

**Issue by Rob-Walter** [SmollClover/Jahresprojekt-FA31#12]

**Comment by Rob-Walter** [comment]
Die Navigationspunkte wurden entsprechend unserer Seitenstruktur angepasst

**Comment by Rob-Walter** [comment]
Das Styling wird von Grund auf neu aufgebaut

**Comment by Rob-Walter** [comment]
Grundlegende Struktur der Navigationsleiste steht

**Comment by SmollClover** [comment]
Wurde gerade gemerged
