### ISSUE TITLE
Mockup erstellen

### ISSUE THREAD

**Issue by SmollClover** [SmollClover/Jahresprojekt-FA31#2]
Grobes Mockup für das Pflichtenheft erstellen

https://www.figma.com/file/nvE5Eu67EEIFxrGMm3M2vK/Untitled?type=design&node-id=1%3A2&mode=design&t=sZfz4EtQAYkZYApc-1

**Comment by Rob-Walter** [comment]
https://www.figma.com/file/nvE5Eu67EEIFxrGMm3M2vK/UI-Proto?type=design&node-id=0-1&mode=design&t=1W71U7wjovP75tpS-0

**Comment by SmollClover** [comment]
Done
